apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ns1-2-echo
spec:
  parentRefs:
    - name: eg
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: echoserver
          namespace: ns1
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /ns1
    - backendRefs:
        - group: ""
          kind: Service
          name: echoserver
          namespace: ns2
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /ns2