apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
apiVersion: v1
kind: Pod
metadata:
  name: echoserver-ns1
  namespace: ns1
  labels:
    app: echoserver
spec:
  containers:
  - image: ealen/echo-server:latest
    imagePullPolicy: IfNotPresent
    name: echoserver
    ports:
    - containerPort: 80
    env:
    - name: PORT
      value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: ns1
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns2
---
apiVersion: v1
kind: Pod
metadata:
  name: echoserver-ns2
  namespace: ns2
  labels:
    app: echoserver
spec:
  containers:
  - image: ealen/echo-server:latest
    imagePullPolicy: IfNotPresent
    name: echoserver
    ports:
    - containerPort: 80
    env:
    - name: PORT
      value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: ns2
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver