apiVersion: v1
kind: Pod
metadata:
  name: test-client
  namespace: default
spec:
  containers:
  - args:
    - "3600"
    command:
    - /bin/sleep
    image: pkgs.k8s.io/ubuntu:latest
    imagePullPolicy: Always
    name: c1
  terminationGracePeriodSeconds: 0